version: "3.8"

services:
   mongodb:
       image: 'mongo'
       volumes:
           - data:/data/db
       environment:
           MONGO_INITDB_ROOT_USERNAME: root
           MONGO_INITDB_ROOT_PASSWORD: example
  
   profile_app:
       build: ./app
       ports:
           - '8100:80'
       depends_on:
           - mongodb
       environment:
           MONGO_USER: root
           MONGO_PASS: example

volumes:
   data: